-- AP world language courses share one framework.
--
-- The six language and culture courses (Spanish, French, German, Italian,
-- Japanese, Chinese) are all built on the same six themes, so the sheet listed
-- them once and the importer read only a handful of rows per course. They came
-- out with six subtopics each, which is a parsing artefact rather than a small
-- course.
--
-- Seeded here in full instead. "[Language] in the World" is substituted per
-- course, so AP Spanish gets "Spanish in the World" rather than a placeholder.

BEGIN;

-- Clear the partial rows first so the count is right rather than merged.
DELETE FROM syllabus_content
WHERE curriculum = 'AP' AND subject LIKE 'AP % Language and Culture';

INSERT INTO syllabus_content (curriculum, subject, topic, subtopic, hl_only) VALUES
  ('AP', 'AP Spanish Language and Culture', 'Topic 1 - Families and Communities', 'Family Structure and Roles', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 1 - Families and Communities', 'Education Communities', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 1 - Families and Communities', 'Social Networking and Relationships', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 1 - Families and Communities', 'Customs and Values', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 1 - Families and Communities', 'Global Citizenship', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 1 - Families and Communities', 'Urban and Rural Communities', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 2 - Language and Culture', 'Customs and Celebrations', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 2 - Language and Culture', 'Linguistics', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 2 - Language and Culture', 'Spanish in the World', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 3 - Art and Creativity', 'Architecture', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 3 - Art and Creativity', 'Artistic Heritage', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 3 - Art and Creativity', 'Beauty and Aesthetics', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 3 - Art and Creativity', 'Fashion and Design', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 3 - Art and Creativity', 'Literature', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 3 - Art and Creativity', 'Visual and Performing Arts', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 4 - Science and Technology', 'Innovations and Emerging Technologies', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 4 - Science and Technology', 'Personal Technology and Communication', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 4 - Science and Technology', 'Science in Everyday Life', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 4 - Science and Technology', 'Societal Impacts of Science and Technology', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 5 - Contemporary Life', 'Education and Careers', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 5 - Contemporary Life', 'Entertainment and Media', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 5 - Contemporary Life', 'Food and Health', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 5 - Contemporary Life', 'Pop Culture', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 5 - Contemporary Life', 'Sports and Leisure', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 5 - Contemporary Life', 'Travel and Tourism', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 6 - Global Contexts', 'Global Communication', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 6 - Global Contexts', 'Natural World and Environmental Issues', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 6 - Global Contexts', 'History', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 6 - Global Contexts', 'Policy and Planning', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 6 - Global Contexts', 'Transportation', false),
  ('AP', 'AP Spanish Language and Culture', 'Topic 6 - Global Contexts', 'Economic Trends and International Trade', false),
  ('AP', 'AP French Language and Culture', 'Topic 1 - Families and Communities', 'Family Structure and Roles', false),
  ('AP', 'AP French Language and Culture', 'Topic 1 - Families and Communities', 'Education Communities', false),
  ('AP', 'AP French Language and Culture', 'Topic 1 - Families and Communities', 'Social Networking and Relationships', false),
  ('AP', 'AP French Language and Culture', 'Topic 1 - Families and Communities', 'Customs and Values', false),
  ('AP', 'AP French Language and Culture', 'Topic 1 - Families and Communities', 'Global Citizenship', false),
  ('AP', 'AP French Language and Culture', 'Topic 1 - Families and Communities', 'Urban and Rural Communities', false),
  ('AP', 'AP French Language and Culture', 'Topic 2 - Language and Culture', 'Customs and Celebrations', false),
  ('AP', 'AP French Language and Culture', 'Topic 2 - Language and Culture', 'Linguistics', false),
  ('AP', 'AP French Language and Culture', 'Topic 2 - Language and Culture', 'French in the World', false),
  ('AP', 'AP French Language and Culture', 'Topic 3 - Art and Creativity', 'Architecture', false),
  ('AP', 'AP French Language and Culture', 'Topic 3 - Art and Creativity', 'Artistic Heritage', false),
  ('AP', 'AP French Language and Culture', 'Topic 3 - Art and Creativity', 'Beauty and Aesthetics', false),
  ('AP', 'AP French Language and Culture', 'Topic 3 - Art and Creativity', 'Fashion and Design', false),
  ('AP', 'AP French Language and Culture', 'Topic 3 - Art and Creativity', 'Literature', false),
  ('AP', 'AP French Language and Culture', 'Topic 3 - Art and Creativity', 'Visual and Performing Arts', false),
  ('AP', 'AP French Language and Culture', 'Topic 4 - Science and Technology', 'Innovations and Emerging Technologies', false),
  ('AP', 'AP French Language and Culture', 'Topic 4 - Science and Technology', 'Personal Technology and Communication', false),
  ('AP', 'AP French Language and Culture', 'Topic 4 - Science and Technology', 'Science in Everyday Life', false),
  ('AP', 'AP French Language and Culture', 'Topic 4 - Science and Technology', 'Societal Impacts of Science and Technology', false),
  ('AP', 'AP French Language and Culture', 'Topic 5 - Contemporary Life', 'Education and Careers', false),
  ('AP', 'AP French Language and Culture', 'Topic 5 - Contemporary Life', 'Entertainment and Media', false),
  ('AP', 'AP French Language and Culture', 'Topic 5 - Contemporary Life', 'Food and Health', false),
  ('AP', 'AP French Language and Culture', 'Topic 5 - Contemporary Life', 'Pop Culture', false),
  ('AP', 'AP French Language and Culture', 'Topic 5 - Contemporary Life', 'Sports and Leisure', false),
  ('AP', 'AP French Language and Culture', 'Topic 5 - Contemporary Life', 'Travel and Tourism', false),
  ('AP', 'AP French Language and Culture', 'Topic 6 - Global Contexts', 'Global Communication', false),
  ('AP', 'AP French Language and Culture', 'Topic 6 - Global Contexts', 'Natural World and Environmental Issues', false),
  ('AP', 'AP French Language and Culture', 'Topic 6 - Global Contexts', 'History', false),
  ('AP', 'AP French Language and Culture', 'Topic 6 - Global Contexts', 'Policy and Planning', false),
  ('AP', 'AP French Language and Culture', 'Topic 6 - Global Contexts', 'Transportation', false),
  ('AP', 'AP French Language and Culture', 'Topic 6 - Global Contexts', 'Economic Trends and International Trade', false),
  ('AP', 'AP German Language and Culture', 'Topic 1 - Families and Communities', 'Family Structure and Roles', false),
  ('AP', 'AP German Language and Culture', 'Topic 1 - Families and Communities', 'Education Communities', false),
  ('AP', 'AP German Language and Culture', 'Topic 1 - Families and Communities', 'Social Networking and Relationships', false),
  ('AP', 'AP German Language and Culture', 'Topic 1 - Families and Communities', 'Customs and Values', false),
  ('AP', 'AP German Language and Culture', 'Topic 1 - Families and Communities', 'Global Citizenship', false),
  ('AP', 'AP German Language and Culture', 'Topic 1 - Families and Communities', 'Urban and Rural Communities', false),
  ('AP', 'AP German Language and Culture', 'Topic 2 - Language and Culture', 'Customs and Celebrations', false),
  ('AP', 'AP German Language and Culture', 'Topic 2 - Language and Culture', 'Linguistics', false),
  ('AP', 'AP German Language and Culture', 'Topic 2 - Language and Culture', 'German in the World', false),
  ('AP', 'AP German Language and Culture', 'Topic 3 - Art and Creativity', 'Architecture', false),
  ('AP', 'AP German Language and Culture', 'Topic 3 - Art and Creativity', 'Artistic Heritage', false),
  ('AP', 'AP German Language and Culture', 'Topic 3 - Art and Creativity', 'Beauty and Aesthetics', false),
  ('AP', 'AP German Language and Culture', 'Topic 3 - Art and Creativity', 'Fashion and Design', false),
  ('AP', 'AP German Language and Culture', 'Topic 3 - Art and Creativity', 'Literature', false),
  ('AP', 'AP German Language and Culture', 'Topic 3 - Art and Creativity', 'Visual and Performing Arts', false),
  ('AP', 'AP German Language and Culture', 'Topic 4 - Science and Technology', 'Innovations and Emerging Technologies', false),
  ('AP', 'AP German Language and Culture', 'Topic 4 - Science and Technology', 'Personal Technology and Communication', false),
  ('AP', 'AP German Language and Culture', 'Topic 4 - Science and Technology', 'Science in Everyday Life', false),
  ('AP', 'AP German Language and Culture', 'Topic 4 - Science and Technology', 'Societal Impacts of Science and Technology', false),
  ('AP', 'AP German Language and Culture', 'Topic 5 - Contemporary Life', 'Education and Careers', false),
  ('AP', 'AP German Language and Culture', 'Topic 5 - Contemporary Life', 'Entertainment and Media', false),
  ('AP', 'AP German Language and Culture', 'Topic 5 - Contemporary Life', 'Food and Health', false),
  ('AP', 'AP German Language and Culture', 'Topic 5 - Contemporary Life', 'Pop Culture', false),
  ('AP', 'AP German Language and Culture', 'Topic 5 - Contemporary Life', 'Sports and Leisure', false),
  ('AP', 'AP German Language and Culture', 'Topic 5 - Contemporary Life', 'Travel and Tourism', false),
  ('AP', 'AP German Language and Culture', 'Topic 6 - Global Contexts', 'Global Communication', false),
  ('AP', 'AP German Language and Culture', 'Topic 6 - Global Contexts', 'Natural World and Environmental Issues', false),
  ('AP', 'AP German Language and Culture', 'Topic 6 - Global Contexts', 'History', false),
  ('AP', 'AP German Language and Culture', 'Topic 6 - Global Contexts', 'Policy and Planning', false),
  ('AP', 'AP German Language and Culture', 'Topic 6 - Global Contexts', 'Transportation', false),
  ('AP', 'AP German Language and Culture', 'Topic 6 - Global Contexts', 'Economic Trends and International Trade', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 1 - Families and Communities', 'Family Structure and Roles', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 1 - Families and Communities', 'Education Communities', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 1 - Families and Communities', 'Social Networking and Relationships', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 1 - Families and Communities', 'Customs and Values', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 1 - Families and Communities', 'Global Citizenship', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 1 - Families and Communities', 'Urban and Rural Communities', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 2 - Language and Culture', 'Customs and Celebrations', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 2 - Language and Culture', 'Linguistics', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 2 - Language and Culture', 'Italian in the World', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 3 - Art and Creativity', 'Architecture', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 3 - Art and Creativity', 'Artistic Heritage', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 3 - Art and Creativity', 'Beauty and Aesthetics', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 3 - Art and Creativity', 'Fashion and Design', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 3 - Art and Creativity', 'Literature', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 3 - Art and Creativity', 'Visual and Performing Arts', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 4 - Science and Technology', 'Innovations and Emerging Technologies', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 4 - Science and Technology', 'Personal Technology and Communication', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 4 - Science and Technology', 'Science in Everyday Life', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 4 - Science and Technology', 'Societal Impacts of Science and Technology', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 5 - Contemporary Life', 'Education and Careers', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 5 - Contemporary Life', 'Entertainment and Media', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 5 - Contemporary Life', 'Food and Health', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 5 - Contemporary Life', 'Pop Culture', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 5 - Contemporary Life', 'Sports and Leisure', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 5 - Contemporary Life', 'Travel and Tourism', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 6 - Global Contexts', 'Global Communication', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 6 - Global Contexts', 'Natural World and Environmental Issues', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 6 - Global Contexts', 'History', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 6 - Global Contexts', 'Policy and Planning', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 6 - Global Contexts', 'Transportation', false),
  ('AP', 'AP Italian Language and Culture', 'Topic 6 - Global Contexts', 'Economic Trends and International Trade', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 1 - Families and Communities', 'Family Structure and Roles', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 1 - Families and Communities', 'Education Communities', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 1 - Families and Communities', 'Social Networking and Relationships', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 1 - Families and Communities', 'Customs and Values', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 1 - Families and Communities', 'Global Citizenship', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 1 - Families and Communities', 'Urban and Rural Communities', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 2 - Language and Culture', 'Customs and Celebrations', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 2 - Language and Culture', 'Linguistics', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 2 - Language and Culture', 'Japanese in the World', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 3 - Art and Creativity', 'Architecture', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 3 - Art and Creativity', 'Artistic Heritage', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 3 - Art and Creativity', 'Beauty and Aesthetics', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 3 - Art and Creativity', 'Fashion and Design', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 3 - Art and Creativity', 'Literature', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 3 - Art and Creativity', 'Visual and Performing Arts', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 4 - Science and Technology', 'Innovations and Emerging Technologies', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 4 - Science and Technology', 'Personal Technology and Communication', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 4 - Science and Technology', 'Science in Everyday Life', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 4 - Science and Technology', 'Societal Impacts of Science and Technology', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 5 - Contemporary Life', 'Education and Careers', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 5 - Contemporary Life', 'Entertainment and Media', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 5 - Contemporary Life', 'Food and Health', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 5 - Contemporary Life', 'Pop Culture', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 5 - Contemporary Life', 'Sports and Leisure', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 5 - Contemporary Life', 'Travel and Tourism', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 6 - Global Contexts', 'Global Communication', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 6 - Global Contexts', 'Natural World and Environmental Issues', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 6 - Global Contexts', 'History', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 6 - Global Contexts', 'Policy and Planning', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 6 - Global Contexts', 'Transportation', false),
  ('AP', 'AP Japanese Language and Culture', 'Topic 6 - Global Contexts', 'Economic Trends and International Trade', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 1 - Families and Communities', 'Family Structure and Roles', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 1 - Families and Communities', 'Education Communities', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 1 - Families and Communities', 'Social Networking and Relationships', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 1 - Families and Communities', 'Customs and Values', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 1 - Families and Communities', 'Global Citizenship', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 1 - Families and Communities', 'Urban and Rural Communities', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 2 - Language and Culture', 'Customs and Celebrations', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 2 - Language and Culture', 'Linguistics', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 2 - Language and Culture', 'Chinese in the World', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 3 - Art and Creativity', 'Architecture', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 3 - Art and Creativity', 'Artistic Heritage', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 3 - Art and Creativity', 'Beauty and Aesthetics', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 3 - Art and Creativity', 'Fashion and Design', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 3 - Art and Creativity', 'Literature', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 3 - Art and Creativity', 'Visual and Performing Arts', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 4 - Science and Technology', 'Innovations and Emerging Technologies', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 4 - Science and Technology', 'Personal Technology and Communication', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 4 - Science and Technology', 'Science in Everyday Life', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 4 - Science and Technology', 'Societal Impacts of Science and Technology', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 5 - Contemporary Life', 'Education and Careers', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 5 - Contemporary Life', 'Entertainment and Media', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 5 - Contemporary Life', 'Food and Health', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 5 - Contemporary Life', 'Pop Culture', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 5 - Contemporary Life', 'Sports and Leisure', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 5 - Contemporary Life', 'Travel and Tourism', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 6 - Global Contexts', 'Global Communication', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 6 - Global Contexts', 'Natural World and Environmental Issues', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 6 - Global Contexts', 'History', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 6 - Global Contexts', 'Policy and Planning', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 6 - Global Contexts', 'Transportation', false),
  ('AP', 'AP Chinese Language and Culture', 'Topic 6 - Global Contexts', 'Economic Trends and International Trade', false)
ON CONFLICT DO NOTHING;

COMMIT;
